# Generated by Django 4.2.2 on 2023-06-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
