# Generated by Django 4.2.2 on 2023-06-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='info',
            field=models.CharField(max_length=2200, null=True),
        ),
    ]
