# Generated by Django 4.2.2 on 2023-06-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rate_system',
            field=models.CharField(max_length=2200, null=True),
        ),
    ]
